server:
  port: 8081

spring:
  datasource:
    url: ${SUPABASE_DB_URL}
    username: ${SUPABASE_DB_USERNAME}
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
        preferQueryMode: simple
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # Tắt cảnh báo hiệu suất open-in-view của Spring Data JPA
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI}
  data:
    redis:
      url: ${REDIS_URL}
      timeout:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
supabase:
  url: ${SUPABASE_API_URL}
  key: ${SUPABASE_API_KEY}
  bucket: ticketrush

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
